# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainframe(object):
    def setupUi(self, mainframe):
        mainframe.setObjectName("mainframe")
        mainframe.resize(600, 600)
        mainframe.setMinimumSize(QtCore.QSize(600, 600))
        mainframe.setMaximumSize(QtCore.QSize(600, 600))
        mainframe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.titleLabel = QtWidgets.QLabel(mainframe)
        self.titleLabel.setGeometry(QtCore.QRect(50, 20, 500, 80))
        self.titleLabel.setMinimumSize(QtCore.QSize(500, 80))
        self.titleLabel.setMaximumSize(QtCore.QSize(500, 80))
        self.titleLabel.setStyleSheet("font: 16pt \"微软雅黑\";\n"
"background: transparent;")
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setWordWrap(True)
        self.titleLabel.setObjectName("titleLabel")
        self.startButton = QtWidgets.QPushButton(mainframe)
        self.startButton.setGeometry(QtCore.QRect(420, 120, 150, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.startButton.setFont(font)
        self.startButton.setStyleSheet("QPushButton{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove #00EE00;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove blue;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:checked{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove blue;\n"
"    border-style: outset;\n"
"}")
        self.startButton.setObjectName("startButton")
        self.logsBrowser = QtWidgets.QTextBrowser(mainframe)
        self.logsBrowser.setGeometry(QtCore.QRect(3, 307, 594, 290))
        self.logsBrowser.setStyleSheet("font: 12pt \"宋体\";\n"
"border: 3px inset gray;")
        self.logsBrowser.setObjectName("logsBrowser")
        self.localUrlLineEdit = QtWidgets.QLineEdit(mainframe)
        self.localUrlLineEdit.setGeometry(QtCore.QRect(0, 200, 100, 40))
        self.localUrlLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.localUrlLineEdit.setStyleSheet("border:none;\n"
"font: 18px \"微软雅黑\";")
        self.localUrlLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.localUrlLineEdit.setObjectName("localUrlLineEdit")
        self.networkUrlLineEdit = QtWidgets.QLineEdit(mainframe)
        self.networkUrlLineEdit.setGeometry(QtCore.QRect(0, 250, 100, 40))
        self.networkUrlLineEdit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.networkUrlLineEdit.setStyleSheet("border:none;\n"
"font: 18px \"微软雅黑\";")
        self.networkUrlLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.networkUrlLineEdit.setObjectName("networkUrlLineEdit")
        self.localUrl = QtWidgets.QPushButton(mainframe)
        self.localUrl.setGeometry(QtCore.QRect(100, 200, 500, 40))
        self.localUrl.setStyleSheet("text-align: left;\n"
"font: 16px \"微软雅黑\";\n"
"padding-left: 10px;\n"
"color: blue;")
        self.localUrl.setObjectName("localUrl")
        self.networkUrl = QtWidgets.QPushButton(mainframe)
        self.networkUrl.setGeometry(QtCore.QRect(100, 250, 500, 40))
        self.networkUrl.setStyleSheet("text-align: left;\n"
"font: 16px \"微软雅黑\";\n"
"padding-left: 10px;\n"
"color: #008B8B;")
        self.networkUrl.setObjectName("networkUrl")
        self.installEnvButton = QtWidgets.QPushButton(mainframe)
        self.installEnvButton.setGeometry(QtCore.QRect(30, 120, 150, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.installEnvButton.setFont(font)
        self.installEnvButton.setStyleSheet("QPushButton{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove #00EE00;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove blue;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:checked{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove blue;\n"
"    border-style: outset;\n"
"}")
        self.installEnvButton.setObjectName("installEnvButton")
        self.installScriptButton = QtWidgets.QPushButton(mainframe)
        self.installScriptButton.setGeometry(QtCore.QRect(225, 120, 150, 50))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.installScriptButton.setFont(font)
        self.installScriptButton.setStyleSheet("QPushButton{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove #00EE00;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:hover{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove blue;\n"
"    border-style: outset;\n"
"}\n"
"QPushButton:checked{\n"
"    font: 12pt \"等线\";\n"
"    border-radius: 20px;\n"
"    border: 2px groove blue;\n"
"    border-style: outset;\n"
"}")
        self.installScriptButton.setObjectName("installScriptButton")

        self.retranslateUi(mainframe)
        QtCore.QMetaObject.connectSlotsByName(mainframe)

    def retranslateUi(self, mainframe):
        _translate = QtCore.QCoreApplication.translate
        mainframe.setWindowTitle(_translate("mainframe", "Chemical-EPS"))
        self.titleLabel.setText(_translate("mainframe", "化工类企业环境事故应急预案演练\n"
"计算机模拟仿真系统"))
        self.startButton.setText(_translate("mainframe", "启动程序"))
        self.logsBrowser.setHtml(_translate("mainframe", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'宋体\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'楷体\';\"><br /></p></body></html>"))
        self.localUrlLineEdit.setText(_translate("mainframe", "本地URL"))
        self.networkUrlLineEdit.setText(_translate("mainframe", "网络URL"))
        self.localUrl.setText(_translate("mainframe", "待识别"))
        self.networkUrl.setText(_translate("mainframe", "待识别"))
        self.installEnvButton.setText(_translate("mainframe", "安装依赖"))
        self.installScriptButton.setText(_translate("mainframe", "下载脚本"))
